# Generated by Django 5.1 on 2025-05-06 16:07

import django.db.models.deletion
import tareas.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', tareas.managers.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(help_text='Calle y número, ej: Calle 100 #15-20', max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(help_text='Ciudad o municipio de recolección', max_length=100, verbose_name='Ciudad/Municipio')),
                ('barrio', models.CharField(blank=True, help_text='Barrio o localidad (opcional)', max_length=100, null=True, verbose_name='Barrio/Localidad')),
                ('referencia', models.CharField(blank=True, help_text='Cerca a... o entre... (opcional)', max_length=255, null=True, verbose_name='Punto de referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recoleccion', to='tareas.factura', verbose_name='Factura asociada')),
            ],
            options={
                'verbose_name': 'Recolección',
                'verbose_name_plural': 'Recolecciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
