# Generated by Django 5.1 on 2025-04-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('factor_co2', models.FloatField(help_text='kg CO₂e evitado por kg de residuo')),
            ],
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='categoria',
        ),
        migrations.CreateModel(
            name='RegistroResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.categoriaresiduo')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.categoriaresiduo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='categorias',
            field=models.ManyToManyField(through='tareas.UbicacionCategoria', to='tareas.categoriaresiduo'),
        ),
    ]
