# Generated by Django 5.1 on 2024-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_cotizaciondomicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.IntegerField()),
                ('operacion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
