# Generated by Django 5.1 on 2025-05-06 01:28

import tareas.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_usuario_email_alter_usuario_identificacion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', tareas.managers.UsuarioManager()),
            ],
        ),
    ]
