# Generated by Django 5.1 on 2025-05-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_recoleccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoleccion',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Recolección', 'verbose_name_plural': 'Recolecciones'},
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='barrio',
            field=models.CharField(blank=True, help_text='Barrio o localidad (opcional)', max_length=100, null=True, verbose_name='Barrio/Localidad'),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='referencia',
            field=models.CharField(blank=True, help_text='Cerca a... o entre... (opcional)', max_length=255, null=True, verbose_name='Punto de referencia'),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='ciudad',
            field=models.CharField(help_text='Ciudad o municipio de recolección', max_length=100, verbose_name='Ciudad/Municipio'),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='direccion',
            field=models.CharField(help_text='Calle y número, ej: Calle 100 #15-20', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recoleccion', to='tareas.factura', verbose_name='Factura asociada'),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones adicionales'),
        ),
    ]
